// Copyright (c) 2026 ancplua
// SPDX-License-Identifier: MIT
//
// maf-model-gen: reflects over the pinned Microsoft.Agents.ObjectModel
// DialogAction hierarchy and writes generated/maf-actions.gen.tsp — the TypeSpec source
// of truth for D2 workflow action shapes (generated, never hand-written).
//
// Run from the repo root:  dotnet run --project tools/maf-model-gen   (or npm run gen:actions)
// Output path overridable as args[0].

using System.Collections;
using System.Reflection;
using System.Text;
using Microsoft.Agents.ObjectModel;

string outPath = Path.GetFullPath(
    args.Length > 0 ? args[0] : Path.Combine("generated", "maf-actions.gen.tsp"));

Assembly asm = typeof(DialogAction).Assembly;
string asmVersion = asm.GetName().Version?.ToString() ?? "unknown";

// Base-class plumbing that is not part of an action's authored YAML shape.
var basePropNames = new HashSet<string>(StringComparer.Ordinal) { "Kind", "HasRequiredProperties" };

var tspKeywords = new HashSet<string>(StringComparer.Ordinal)
{
    "model", "op", "namespace", "interface", "union", "enum", "scalar", "alias", "dec",
    "extern", "fn", "using", "import", "is", "extends", "valueof", "void", "never",
    "unknown", "true", "false", "null", "if", "else", "return",
};

Type actionBase = typeof(DialogAction);
var actions = asm.GetExportedTypes()
    .Where(t => actionBase.IsAssignableFrom(t) && t != actionBase && !t.IsAbstract && !t.IsGenericTypeDefinition)
    .OrderBy(t => t.Name, StringComparer.Ordinal)
    .ToList();

var sb = new StringBuilder();
sb.Append("// <auto-generated/>\n");
sb.Append($"// DO NOT EDIT. Generated by tools/maf-model-gen from Microsoft.Agents.ObjectModel {asmVersion}.\n");
sb.Append("// Regenerate: `npm run gen:actions`. Source of truth = the ObjectModel DialogAction\n");
sb.Append("// hierarchy. Pin bump -> regenerate -> diff review, never hand-port.\n");
sb.Append("// v0 fidelity: complex value types map to `unknown`; `kind` is the YAML discriminator\n");
sb.Append("// (the action's type name). All action properties are optional in v0.\n\n");
sb.Append("namespace AgentFramework.Actions;\n\n");

int count = 0;
foreach (Type t in actions)
{
    var props = t.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
        .Where(p => p.GetIndexParameters().Length == 0 && !basePropNames.Contains(p.Name))
        .ToList();

    sb.Append($"/** MAF workflow action `{t.Name}` (`kind: {t.Name}`). */\n");
    sb.Append($"model {t.Name} {{\n");
    sb.Append($"  kind: \"{t.Name}\";\n");
    foreach (var p in props)
    {
        sb.Append($"  {MemberName(p.Name)}?: {MapType(p.PropertyType)};\n");
    }
    sb.Append("}\n\n");
    count++;
}

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"wrote {count} action models from Microsoft.Agents.ObjectModel {asmVersion} -> {outPath}");
return 0;

string MemberName(string pascal)
{
    string camel = char.ToLowerInvariant(pascal[0]) + pascal[1..];
    return IsSafeIdent(camel) ? camel : $"\"{camel}\"";
}

bool IsSafeIdent(string s)
{
    if (s.Length == 0 || !(char.IsLetter(s[0]) || s[0] == '_')) return false;
    foreach (char c in s)
    {
        if (!(char.IsLetterOrDigit(c) || c == '_')) return false;
    }
    return !tspKeywords.Contains(s);
}

string MapType(Type type)
{
    Type u = Nullable.GetUnderlyingType(type) ?? type;

    if (u == typeof(string)) return "string";
    if (u == typeof(bool)) return "boolean";
    if (u == typeof(byte) || u == typeof(short) || u == typeof(int)) return "int32";
    if (u == typeof(long)) return "int64";
    if (u == typeof(float)) return "float32";
    if (u == typeof(double) || u == typeof(decimal)) return "float64";
    if (u.IsEnum) return "string"; // enums serialize to their string name in YAML

    if (u.IsArray) return MapType(u.GetElementType()!) + "[]";
    if (u != typeof(string) && typeof(IEnumerable).IsAssignableFrom(u) && u.IsGenericType)
    {
        Type[] args = u.GetGenericArguments();
        if (args.Length == 1) return MapType(args[0]) + "[]";
    }

    return "unknown"; // complex ObjectModel value types (v0)
}
